---
- name: install
  hosts: all
  roles:
    - 01-install-packages
    - 02-ceph-preconfig

- name: admin-ntp-config
  hosts: admin
  roles:
    - 03-admin-ntp-config

- name: osd-ntp-config
  hosts: osd
  roles:
    - 04-node-ntp-config

#- name: monitoring-node-config
#  hosts: mon
#  remote_user: root
#  roles:
#    - 05-ceph-monitor-config
#
#- name: osd-node-config
#  hosts: osd
#  roles:
#    - 06-ceph-osd-config
- name: generate-ssh-key
  hosts: admin
  roles:
    - 07-ssh-config
- name: copy ssh key
  hosts: osd
  roles:
    - 07-ssh-key-copy

- name: ceph-deploy
  hosts: osd
  roles:
    - 08-ceph-deploy
    - 09-cephfs-mount