---
- name: create cluster folder
  file:
    path: ~/ceph
    state: directory
    mode: 0755

- name: add Ceph yum repository
  copy:
    src: ceph.conf
    dest: ~/ceph/ceph.conf
    mode: 0644

#- name: install ceph on all nodes
#  shell: ceph-deploy install "{{ item }}"
#  with_items: "{{groups['mon']}}"
#  args:
#    chdir: ~/ceph

- name: create new cluster
  shell: ceph-deploy new node1 node2 node3
  args:
    chdir: ~/ceph

#shell: ceph-deploy --overwrite-conf mon create-initial
- name: deploy the monitor node
  shell: ceph-deploy mon create-initial
  args:
    chdir: ~/ceph

- name: copy configuration file and admin key
  shell: ceph-deploy admin "{{ item }}"
  with_items: "{{groups['mon']}}"
  args:
    chdir: ~/ceph

- name: copy configuration file and admin key
  shell: ceph-deploy mgr create "{{ item }}"
  with_items: "{{groups['mon']}}"
  args:
    chdir: ~/ceph

- name: add OSDs
  shell: "ceph-deploy osd create {{ item }} --data /dev/sdb"
  with_items: "{{groups['osd']}}"
  args:
    chdir: ~/ceph

- name: add metadata server
  shell: "ceph-deploy mds create {{ item }} "
  with_items: "{{groups['osd']}}"
  args:
    chdir: ~/ceph