---
- name: Disable SELinux
  selinux:
    state: disabled

- name: "Ceph monitors firewall enable"
  command: firewall-cmd --zone=public --add-service=ceph-mon --permanent
- name: "OSDs and MDSs firewall enable"
  command: firewall-cmd --zone=public --add-service=ceph --permanent
- name: "setup firewall for public-zone"
  command: firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 source address=192.168.2.0/24 accept'
- name: "reload firewall settings"
  command: firewall-cmd --reload

- name: "set iptables"
  iptables:
    chain: INPUT
    in_interface: ens33
    source: 192.168.2.0/24
    protocol: tcp
    destination_port: 6800:7300
    jump: ACCEPT

- name: "set iptables"
  iptables:
    chain: INPUT
    in_interface: ens33
    source: 192.168.2.0/24
    protocol: tcp
    destination_port: "6789"
    jump: ACCEPT

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
#  with_items: "{{groups['all']}}"

#- name: run ssh-keyscan to add keys to known_hosts
#  shell: "ssh-keyscan {{ item }} >> ~/.ssh/known_hosts"
#  with_items: "{{groups['all']}}"

#- name: run ssh-copy-id
#  shell: "ssh-copy-id root@{{ item }} "
#  with_items: "{{groups['all']}}"
