#---
#- name: delete osd disk partition
#  shell: ceph-deploy disk zap "{{item}}":sdb
#  with_items: "{{groups['osd']}}"
#  args:
#    chdir: ~/ceph

- name: purge node
  shell: ceph-deploy purge "{{ item }}"
  with_items: "{{groups['osd']}}"
  args:
    chdir: ~/ceph

- name: purge node data
  shell: ceph-deploy purgedata "{{ item }}"
  with_items: "{{groups['osd']}}"
  args:
    chdir: ~/ceph

- name: remove keys
  shell: ceph-deploy forgetkeys
  args:
    chdir: ~/cluster
- name: remove ceph related files
  file:
    path: "{{item}}"
    state: absent
  with_fileglob:
    - ceph.*
  args:
    chdir: ~/ceph